### ISSUE TITLE
About the source code

### ISSUE THREAD

**Issue by 1z2z** [CLinvx/HPM-MVS#2]
When will all the codes be uploaded? Thanks.

**Comment by CLinvx** [comment]
Thanks for your attention. The codes have not been organized and they will be released successively after summer vacation.

**Comment by Yin-maple** [comment]
float good_threshold = 0.8 * (-iter * iter * iter_tmp / 90.0)？  0.8 * exp(-iter * iter * iter_tmp / 90.0)
